# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the square-root Lasso
#'
#' Compute the square-root Lasso solution and its residuals for the nodewise Lasso.
#' @param y Response variable.
#' @param X Matrix of regressors.
#' @param lambda Regularization parameter.
#' @details The software is adapted from the Matlab-software provided by Belloni, Chernozhukov
#' and Wang (2011) in https://faculty.fuqua.duke.edu/~abn5/belloni-software.html
#' @export
sqrt_lasso <- function(y, X, lambda) {
    .Call('_PredictingBlackSwans_sqrt_lasso', PACKAGE = 'PredictingBlackSwans', y, X, lambda)
}

